[workspace]
resolver = "3"
members = [
    "crates/*",
]

[workspace.package]
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/kylekingcdn/elme-rs"
license = "MIT"
publish = true

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
async-channel = { version = "2.5.0", default-features = false }
chrono = { version = "0.4.45", default-features = false } #, features = ["std", "now"] }
color-eyre = { version = "0.6.5", default-features = false }
config = { version = "0.15.25", default-features = false }
console = { version = "0.16.6", default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
indicatif = { version = "0.18.6", default-features = false } #, features = ["tokio"] }
lib-conf = { version = "0.3.1", default-features = false }
lib-conf-ports = { version = "0.3.0", default-features = false }
rand = { version = "0.9", default-features = false }
secrecy = { version = "0.10.3", default-features = false } #, features = ["serde"] }
serde = { version = "1.0.229", default-features = false } #, features = ["std", "derive"] }
sqlx = { version = "0.8.6", default-features = false } #, features = ["macros", "migrate", "postgres", "runtime-tokio"] }
thiserror = { version = "2.0.20", default-features = false }
tokio = { version = "1.53.1", default-features = false }
tokio-util = { version = "0.7.19", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
