[package]
name = "elme-db"
description = "elme module - sqlx databases"
version = "0.0.3"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
#default = ["op-traits"]
## Include traits used for repo operations (insert, batch insert, delete, etc)
op-traits = []

[dependencies]
secrecy.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
