[package]
name = "elme-db"
description = "elme module - sqlx databases"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
repo-traits = []

[dependencies]
sqlx.workspace = true
