[package]
name = "elme"
description = "Framework of common glue code for Rust binaries"
version = "0.0.2"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
#default = ["config", "db", "db-op-traits"]
## Enables the `elme-config` module
config = ["dep:elme-config"]
## Enables the `elme-db` module
db = ["dep:elme-db"]
## Enables the `op-traits` feature of the `db` module
db-op-traits = ["db", "elme-db/op-traits"]
## Enables the `elme-error` module
error = ["dep:elme-error"]
## Enables the `elme-otel` module
otel = ["dep:elme-otel"]

[dependencies]
elme-config = { version = "0.0.2", path = "../elme-config", optional = true }
elme-db = { version = "0.0.2", path = "../elme-db", optional = true }
elme-error = { version = "0.0.1", path = "../elme-error", optional = true }
elme-otel = { version = "0.0.1", path = "../elme-otel", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
